name: Terraform Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}


jobs:
  terraform:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Debug - List files
      run: ls -la && echo "---" && find . -name "*.tfvars" -o -name "*.tf"

    # 注意：这里不再需要单独的环境变量！
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan 
      run: terraform plan -var-file="./environments/dev.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve